---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: microserve
  password:
    secure: "jwm4t+L+cNdoKkYoXpwmm92uGyU6jBAN+VurxDFSzqBz7uG/RurueIaLVaBHCSvpXzXE+qOFUrCqhNK7vbBtqIcQajkbf9M/a2i73r7JCGhNg72XfnYuloyWGkvB4xMsGhSmPVOnVmK4h5qUGs8i5Vw2KMYbJnqhj4bAmXwZgS/CbaGE7woTf53CI7CgYe04i6SC0X4PRJTh2F9a9M4Ln1XdoJ59IeZ2k6cDKcL+vNL+Wgz8ibXuWIu9On0VFOLYtfjioGdYj08jvdtxA8gJdglr/q98GgOqxWHOlwiZepxz7zyorXdVzHQbzjXSLNwnlR4H1KSwtVTr7aWYda6xmYaFyAxkj0+e1RX8OwNsyLt+v0aG5ko92M6Xmoxqy2tAwD9grGBTZjqst+422QKz2+D1IwloOhpvzN3GsY+MjakCmm4GNLRJjO8MWIdieXTXG40SA1UjYg5/jj9eZA3aLXGb4y1kM9rUMBh/Ld/wYCLbGZJydsGpk0jSZKxCtMGzDd46b1gjkqRM0pt9+kD3ohmQtsd3jMbXVySdICsYIEo2Q/qPIh+H3GyCRLlOfYzScQFicD2DJWF6jFQquM+ZXHITFZFDPzPMK5pNQ0132BOCYln5fAAc2xx08NHXkB8RQyilzzFl33MBx6/vNnB/DtTTClHtGnJa65H9FIzQ/lk="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
